name: create-from-template
on: create
jobs:
  npm-update:
    if: github.ref == 'refs/heads/main'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: NPM Update
      - run: npm init -y
