name: update-deps
on: [create]
jobs:
  npm-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: node -v
      - run: npm -v
      - run: npm update --save
      - uses: EndBug/add-and-commit@v7.0.0
        with:
          add: '.'
          push: true
