name: learn-github-actions
on: [create]
jobs:
  install-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions-x/commit@v1
      - run: npm init -y
      - run: npm install react --save
      - run: git add -A
      - run: git commit -m "committing updates"
        
